export const QUIZ_QUES_GAP_MILLISECONDS = 10 * 1000;

export const QUIZ_QUES_GAP_SECS = 10;

export const WAIT_TIME_BEFORE_QUIZ_START_SECS = 5;
export const WAIT_TIME_BEFORE_QUIZ_STOP_MILLISECONDS = 5 * 1000;
